INSERT INTO source_registry (
  source_name, family, base_url, cadence, licence, cost, trust_tier, geo_rule, phase, rights_notes, enabled
) VALUES
  (
    'city_vancouver_business_licences',
    'directory/regulatory',
    'https://opendata.vancouver.ca/explore/dataset/business-licences/',
    'daily',
    'City of Vancouver Open Data Portal terms',
    'free',
    'official',
    'BC gate required; City and province fields must resolve to Vancouver, BC; coordinates must pass Metro Vancouver bbox.',
    0,
    'needs_review: confirm production attribution and Open Data licence obligations before launch.',
    TRUE
  ),
  (
    'bc_data_catalogue',
    'geography/data',
    'https://catalogue.data.gov.bc.ca/',
    'varies',
    'BC Open Government Licence',
    'free',
    'official',
    'Boundary source for BC/Metro Vancouver validation.',
    0,
    'needs_review: select authoritative boundary dataset and attribution language before production.',
    FALSE
  ),
  (
    'orgbook_bc',
    'organization',
    'https://orgbook.gov.bc.ca/',
    'daily/weekly',
    'BC Gov public registry access terms',
    'free',
    'official',
    'BC registered organizations only.',
    1,
    'needs_review: validate API terms and data retention rules before adapter enablement.',
    FALSE
  ),
  (
    'osm_overpass',
    'directory',
    'https://overpass-api.de/',
    'weekly',
    'Open Database License',
    'free',
    'community',
    'Metro Vancouver bbox plus bc_gate; cache and rate-limit required.',
    1,
    'needs_review: confirm ODbL attribution/share-alike handling before production use.',
    FALSE
  ),
  (
    'municipal_facilities',
    'directory/public_recreation',
    'https://opendata.vancouver.ca/',
    'weekly',
    'municipal open data terms',
    'free',
    'official',
    'Metro Vancouver municipal facility records; every geo record must pass bc_gate.',
    1,
    'Aggregate adapter over source-specific municipal open data rows. Confirm attribution display for each municipality before production launch.',
    FALSE
  ),
  (
    'municipal_facilities_west_vancouver',
    'directory/public_recreation',
    'https://www.arcgis.com/home/item.html?id=3d1cfad854f246d98b1e04bff9819b3f',
    'weekly',
    'Open Government Licence - West Vancouver',
    'free',
    'official',
    'District of West Vancouver parks/facilities only; coordinates must pass bc_gate.',
    1,
    'District ArcGIS item states District of West Vancouver attribution; licence info points to the Open Government Licence - West Vancouver.',
    FALSE
  ),
  (
    'municipal_facilities_vancouver',
    'directory/public_recreation',
    'https://opendata.vancouver.ca/explore/dataset/parks-facilities/',
    'weekly',
    'City of Vancouver Open Data Portal terms',
    'free',
    'official',
    'City of Vancouver parks/facility records only; coordinates must pass bc_gate.',
    1,
    'City of Vancouver parks facilities and parks datasets are published on the Open Data Portal; verify final attribution copy before production launch.',
    FALSE
  ),
  (
    'municipal_facilities_surrey',
    'directory/public_recreation',
    'https://opendata-surrey.hub.arcgis.com/',
    'weekly',
    'Open Government Licence - City of Surrey',
    'free',
    'official',
    'City of Surrey parks recreation records only; coordinates must pass bc_gate.',
    1,
    'Surrey Open Data Catalog advertises downloadable open data under the Open Government Licence; verify attribution copy before production launch.',
    FALSE
  ),
  (
    'municipal_facilities_burnaby',
    'directory/public_recreation',
    'https://opendata-burnaby.hub.arcgis.com/',
    'weekly',
    'City of Burnaby Open Data terms',
    'free',
    'official',
    'City of Burnaby parks and recreation civic places only; coordinates must pass bc_gate.',
    1,
    'Burnaby Open Data Hub provides civic places and parks/recreation layers; verify attribution and terms before production launch.',
    FALSE
  ),
  (
    'municipal_facilities_richmond',
    'directory/public_recreation',
    'https://www.richmond.ca/services/digital/maps.htm',
    'weekly',
    'needs_review',
    'free',
    'official',
    'Do not fetch until a clean open endpoint and rights terms are confirmed.',
    1,
    'needs_review: Richmond maps page found, but no clean open GeoJSON/CSV/ArcGIS endpoint was confirmed for this milestone.',
    FALSE
  ),
  (
    'municipal_facilities_north_vancouver',
    'directory/public_recreation',
    'https://geoweb.dnv.org/data/',
    'weekly',
    'needs_review',
    'free',
    'official',
    'Do not fetch until a clean open endpoint and rights terms are confirmed.',
    1,
    'needs_review: North Vancouver GEOweb exposes downloadable datasets, but a clean direct facility endpoint was not adopted for this milestone.',
    FALSE
  ),
  (
    'local_rss',
    'feed',
    NULL,
    'hourly/daily',
    'source-specific',
    'free',
    'reputable_press',
    'BC-local outlet allowlist and bc_gate for geocoded records.',
    1,
    'needs_review: per-feed copyright and excerpt policy required.',
    FALSE
  ),
  (
    'bc_gov_news_rss',
    'regulatory/feed',
    'https://news.gov.bc.ca/',
    'hourly/daily',
    'BC Government website terms',
    'free',
    'official',
    'Province 59 / BC text scope; bc_gate for geocoded records.',
    1,
    'needs_review: confirm republication limits and attribution requirements.',
    FALSE
  ),
  (
    'health_canada_recalls',
    'recall/feed',
    'https://recalls-rappels.canada.ca/',
    'as_published',
    'Government of Canada terms',
    'free',
    'official',
    'Canada-wide source filtered to BC relevance where applicable.',
    1,
    'needs_review: confirm recall feed licence and attribution before adapter enablement.',
    FALSE
  ),
  (
    'vch_fraser_health_pages',
    'regulatory/context',
    'https://www.vch.ca/',
    'weekly/daily',
    'source-specific',
    'free',
    'official',
    'VCH/FHA jurisdiction and bc_gate for geocoded records.',
    1,
    'needs_review: source-specific scrape permission and retention review required.',
    FALSE
  ),
  (
    'healthlink_bc_locator',
    'directory/context',
    'https://www.healthlinkbc.ca/',
    'weekly/manual',
    'source-specific',
    'free',
    'official',
    'BC service locator only.',
    1,
    'needs_review: validate access pattern and terms before adapter enablement.',
    FALSE
  ),
  (
    'clinicaltrials_gov',
    'trial/people',
    'https://clinicaltrials.gov/',
    'weekdays',
    'public domain / source terms',
    'free',
    'official',
    'BC sites only; no patient data.',
    1,
    'needs_review: confirm use of public trial metadata and attribution.',
    FALSE
  ),
  (
    'workbc_job_bank',
    'jobs',
    'https://www.workbc.ca/',
    'daily',
    'source-specific',
    'free',
    'official',
    'BC-filtered job locations only.',
    1,
    'needs_review: confirm API/feed access and posting excerpt policy.',
    FALSE
  ),
  (
    'gdelt_doc',
    'feed',
    'https://www.gdeltproject.org/',
    '15_min/daily',
    'GDELT terms',
    'free',
    'community',
    'BC-local relevance filter; corroborate before high severity.',
    1,
    'needs_review: confirm rights and source-link display requirements.',
    FALSE
  )
ON CONFLICT (source_name) DO UPDATE SET
  family = EXCLUDED.family,
  base_url = EXCLUDED.base_url,
  cadence = EXCLUDED.cadence,
  licence = EXCLUDED.licence,
  cost = EXCLUDED.cost,
  trust_tier = EXCLUDED.trust_tier,
  geo_rule = EXCLUDED.geo_rule,
  phase = EXCLUDED.phase,
  rights_notes = EXCLUDED.rights_notes,
  enabled = EXCLUDED.enabled,
  updated_at = now();
